#!/bin/bash

# Configuration and Initialization
clear

# User Input for Target Area
read -p "Enter the GCP ZONE: " TARGET_ZONE
export ZONE="$TARGET_ZONE"
export REGION="${ZONE%-*}"

# Generate the initial deployment payload
cat > run_setup.sh <<'EOF_SETUP'
gcloud auth login --quiet

export PROJECT_ID=$(gcloud config get-value project)

export ZONE=$(gcloud compute project-info describe \
--format="value(commonInstanceMetadata.items[google-compute-default-zone])")

gcloud iam service-accounts create devops --display-name devops

gcloud config configurations activate default

gcloud iam service-accounts list --filter "displayName=devops"

TARGET_SA=$(gcloud iam service-accounts list --format="value(email)" --filter "displayName=devops")

gcloud projects add-iam-policy-binding $PROJECT_ID \
  --member="serviceAccount:$TARGET_SA" \
  --role="roles/iam.serviceAccountUser"

gcloud projects add-iam-policy-binding $PROJECT_ID \
  --member="serviceAccount:$TARGET_SA" \
  --role="roles/compute.instanceAdmin"

gcloud compute instances create vm-2 --project=$PROJECT_ID --zone=$ZONE --service-account=$TARGET_SA --scopes=https://www.googleapis.com/auth/bigquery

cat > role-definition.yaml <<EOF
title: Custom Role
description: Custom role with cloudsql.instances.connect and cloudsql.instances.get permissions
includedPermissions:
- cloudsql.instances.connect
- cloudsql.instances.get
EOF

gcloud iam roles create customRole --project=$PROJECT_ID --file=role-definition.yaml

gcloud iam service-accounts create bigquery-qwiklab --display-name bigquery-qwiklab

TARGET_SA=$(gcloud iam service-accounts list --format="value(email)" --filter "displayName=bigquery-qwiklab")

gcloud projects add-iam-policy-binding $PROJECT_ID --member=serviceAccount:$TARGET_SA --role=roles/bigquery.dataViewer
gcloud projects add-iam-policy-binding $PROJECT_ID --member=serviceAccount:$TARGET_SA --role=roles/bigquery.user

gcloud compute instances create bigquery-instance --project=$PROJECT_ID --zone=$ZONE --service-account=$TARGET_SA --scopes=https://www.googleapis.com/auth/bigquery
EOF_SETUP

for i in {1..10}; do
  sleep 1
done

export PROJECT_ID=$(gcloud config get-value project)

gcloud compute scp run_setup.sh lab-vm:/tmp --project=$PROJECT_ID --zone=$ZONE --quiet

gcloud compute ssh lab-vm --project=$PROJECT_ID --zone=$ZONE --quiet --command="bash /tmp/run_setup.sh"

wait_timer=45
for i in $(seq 1 $wait_timer); do
  sleep 1
done

# Generate the runtime pipeline payload
cat > run_setup.sh <<'EOF_SETUP'
sudo apt-get update

sudo apt install python3 -y
sudo apt-get install -y git python3-pip
sudo apt install python3.11-venv -y

python3 -m venv create myvenv
source myvenv/bin/activate

pip3 install --upgrade pip
pip3 install google-cloud-bigquery
pip3 install pyarrow
pip3 install pandas
pip3 install db-dtypes
pip3 install --upgrade google-cloud

export PROJECT_ID=$(gcloud config get-value project)
export SERVICE_ACCOUNT_EMAIL=$(curl -s "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/email" -H "Metadata-Flavor: Google")

echo "
from google.auth import compute_engine
from google.cloud import bigquery
credentials = compute_engine.Credentials(
service_account_email='$SERVICE_ACCOUNT_EMAIL')
query = '''
SELECT name, SUM(number) as total_people
FROM \"bigquery-public-data.usa_names.usa_1910_2013\"
WHERE state = 'TX'
GROUP BY name, state
ORDER BY total_people DESC
LIMIT 20
'''
client = bigquery.Client(
  project='$PROJECT_ID',
  credentials=credentials)
print(client.query(query).to_dataframe())
" > query.py

sleep 10

python3 query.py
EOF_SETUP

wait_timer=10
for i in $(seq 1 $wait_timer); do
  sleep 1
done

export PROJECT_ID=$(gcloud config get-value project)

gcloud compute scp run_setup.sh bigquery-instance:/tmp --project=$PROJECT_ID --zone=$ZONE --quiet

gcloud compute ssh bigquery-instance --project=$PROJECT_ID --zone=$ZONE --quiet --command="bash /tmp/run_setup.sh"
