#!/bin/bash

ZONE=$(gcloud compute project-info describe \
  --format="value(commonInstanceMetadata.items[google-compute-default-zone])" 2>/dev/null)
REGION=$(gcloud compute project-info describe \
  --format="value(commonInstanceMetadata.items[google-compute-default-region])" 2>/dev/null)
PROJECT_ID=$(gcloud config get-value project 2>/dev/null)

if [ -z "$ZONE" ]; then
    read -p "Zone: " ZONE
    REGION=${ZONE%-*}
fi

for i in {1..3}; do
    gcloud compute instances create "web$i" \
        --zone="$ZONE" \
        --machine-type=e2-small \
        --tags=network-lb-tag \
        --image-family=debian-12 \
        --image-project=debian-cloud \
        --metadata=startup-script='#!/bin/bash
        apt-get update
        apt-get install apache2 -y
        service apache2 restart
        echo "<h3>Web Server: web'$i'</h3>" | tee /var/www/html/index.html' > /dev/null 2>&1 &
done
wait

gcloud compute firewall-rules create www-firewall-network-lb \
    --allow tcp:80 \
    --target-tags network-lb-tag > /dev/null 2>&1

gcloud compute addresses create network-lb-ip-1 \
    --region="$REGION" > /dev/null 2>&1

gcloud compute http-health-checks create basic-check > /dev/null 2>&1

gcloud compute target-pools create www-pool \
    --region="$REGION" \
    --http-health-check basic-check > /dev/null 2>&1

gcloud compute target-pools add-instances www-pool \
    --instances web1,web2,web3 \
    --zone="$ZONE" > /dev/null 2>&1

gcloud compute forwarding-rules create www-rule \
    --region="$REGION" \
    --ports 80 \
    --address network-lb-ip-1 \
    --target-pool www-pool > /dev/null 2>&1

gcloud compute instance-templates create lb-backend-template \
   --region="$REGION" \
   --network=default \
   --subnet=default \
   --tags=allow-health-check \
   --machine-type=e2-medium \
   --image-family=debian-12 \
   --image-project=debian-cloud \
   --metadata=startup-script='#!/bin/bash
     apt-get update
     apt-get install apache2 -y
     a2ensite default-ssl
     a2enmod ssl
     vm_hostname="$(curl -H "Metadata-Flavor:Google" \
     http://169.254.169.254/computeMetadata/v1/instance/name)"
     echo "Page served from: $vm_hostname" | \
     tee /var/www/html/index.html
     systemctl restart apache2' > /dev/null 2>&1

gcloud compute instance-groups managed create lb-backend-group \
   --template=lb-backend-template \
   --size=2 \
   --zone="$ZONE" > /dev/null 2>&1

gcloud compute firewall-rules create fw-allow-health-check \
  --network=default \
  --action=allow \
  --direction=ingress \
  --source-ranges=130.211.0.0/22,35.191.0.0/16 \
  --target-tags=allow-health-check \
  --rules=tcp:80 > /dev/null 2>&1

gcloud compute addresses create lb-ipv4-1 \
  --ip-version=IPV4 \
  --global > /dev/null 2>&1

gcloud compute health-checks create http http-basic-check \
  --port 80 > /dev/null 2>&1

gcloud compute backend-services create web-backend-service \
  --protocol=HTTP \
  --port-name=http \
  --health-checks=http-basic-check \
  --global > /dev/null 2>&1

gcloud compute backend-services add-backend web-backend-service \
  --instance-group=lb-backend-group \
  --instance-group-zone="$ZONE" \
  --global > /dev/null 2>&1

gcloud compute url-maps create web-map-http \
    --default-service web-backend-service > /dev/null 2>&1

gcloud compute target-http-proxies create http-lb-proxy \
    --url-map web-map-http > /dev/null 2>&1

gcloud compute forwarding-rules create http-content-rule \
    --address=lb-ipv4-1 \
    --global \
    --target-http-proxy=http-lb-proxy \
    --ports=80 > /dev/null 2>&1
