#!/bin/bash

echo "Setting the below values statically"

# Assign static values
BUCKET="qwiklabs-gcp-01-8908a6b23458-bucket"
REGION="us-central1"
BUCKET_NAME="my-new-bucket-name"

# Validate the variables
if [[ -z $BUCKET || -z $REGION || -z $BUCKET_NAME ]]; then
    echo "Error: One or more required variables are not set!"
    exit 1
fi

echo "The set values are:"
echo "BUCKET: $BUCKET"
echo "REGION: $REGION"
echo "BUCKET_NAME: $BUCKET_NAME"

# Run gcloud commands
gcloud storage buckets create gs://$BUCKET_NAME --location=$REGION
gcloud storage cp --recursive gs://$BUCKET/* gs://$BUCKET_NAME
gcloud storage buckets update gs://$BUCKET_NAME --no-uniform-bucket-level-access
gcloud storage buckets add-iam-policy-binding gs://$BUCKET_NAME --member=allUsers --role=roles/storage.admin
gcloud storage buckets update gs://$BUCKET_NAME --web-main-page-suffix=index.html --web-error-page=error.html

gcloud compute addresses create example-ip --network-tier=PREMIUM --ip-version=IPV4 --global
gcloud compute addresses describe example-ip --format="get(address)" --global
gcloud compute backend-buckets create cp-backend-bucket --gcs-bucket-name=$BUCKET_NAME
gcloud compute url-maps create cp-load-balancer --default-backend-bucket=cp-backend-bucket
gcloud compute target-http-proxies create cp-tp --url-map=cp-load-balancer
gcloud compute forwarding-rules create cp-ff --load-balancing-scheme=EXTERNAL --network-tier=PREMIUM --target-http-proxy=cp-tp --ports=80 --address=example-ip --global

# Wait for resources to stabilize
sleep 30

# Get IP address
IP_ADDRESS=$(gcloud compute addresses describe example-ip --format="get(address)" --global)

echo "This is the IP address: $IP_ADDRESS"

# Test the setup
curl http://$IP_ADDRESS
