#!/bin/bash

gcloud config set project $(gcloud projects list \
--format='value(PROJECT_ID)' \
--filter='qwiklabs-gcp')

export REGION=$(gcloud compute project-info describe \
--format="value(commonInstanceMetadata.items[google-compute-default-region])")

export DATASET_SERVICE=netflix-dataset-service
export FRONTEND_STAGING_SERVICE=frontend-staging-service
export FRONTEND_PRODUCTION_SERVICE=frontend-production-service

gcloud services enable \
run.googleapis.com \
cloudbuild.googleapis.com \
artifactregistry.googleapis.com \
firestore.googleapis.com

gcloud firestore databases create \
--location=$REGION

gcloud artifacts repositories create rest-api-repo \
--repository-format=docker \
--location=$REGION

git clone https://github.com/rosera/pet-theory.git

# Import CSV Data
cd ~/pet-theory/lab06/firebase-import-csv/solution

npm install

node index.js netflix_titles_original.csv

# REST API v0.1
cd ~/pet-theory/lab06/firebase-rest-api/solution-01

npm install

gcloud builds submit \
--tag $REGION-docker.pkg.dev/$DEVSHELL_PROJECT_ID/rest-api-repo/rest-api:0.1

gcloud run deploy $DATASET_SERVICE \
--image $REGION-docker.pkg.dev/$DEVSHELL_PROJECT_ID/rest-api-repo/rest-api:0.1 \
--allow-unauthenticated \
--max-instances=1 \
--region=$REGION \
--quiet

SERVICE_URL=$(gcloud run services describe $DATASET_SERVICE \
--region=$REGION \
--format='value(status.url)')

curl -X GET $SERVICE_URL

# REST API v0.2
cd ~/pet-theory/lab06/firebase-rest-api/solution-02

npm install

gcloud builds submit \
--tag $REGION-docker.pkg.dev/$DEVSHELL_PROJECT_ID/rest-api-repo/rest-api:0.2

gcloud run deploy $DATASET_SERVICE \
--image $REGION-docker.pkg.dev/$DEVSHELL_PROJECT_ID/rest-api-repo/rest-api:0.2 \
--allow-unauthenticated \
--max-instances=1 \
--region=$REGION \
--quiet

SERVICE_URL=$(gcloud run services describe $DATASET_SERVICE \
--region=$REGION \
--format='value(status.url)')

curl -X GET $SERVICE_URL/2019

# Staging Frontend
cd ~/pet-theory/lab06/firebase-frontend

npm install

npm run build

gcloud builds submit \
--tag $REGION-docker.pkg.dev/$DEVSHELL_PROJECT_ID/rest-api-repo/frontend-staging:0.1

gcloud run deploy $FRONTEND_STAGING_SERVICE \
--image $REGION-docker.pkg.dev/$DEVSHELL_PROJECT_ID/rest-api-repo/frontend-staging:0.1 \
--platform managed \
--region=$REGION \
--max-instances=1 \
--allow-unauthenticated \
--quiet

# Production Frontend
cd ~/pet-theory/lab06/firebase-frontend/public

sed -i "s|const REST_API_SERVICE = \".*\"|const REST_API_SERVICE = \"$SERVICE_URL\"|g" app.js

cd ~/pet-theory/lab06/firebase-frontend

gcloud builds submit \
--tag $REGION-docker.pkg.dev/$DEVSHELL_PROJECT_ID/rest-api-repo/frontend-production:0.1

gcloud run deploy $FRONTEND_PRODUCTION_SERVICE \
--image $REGION-docker.pkg.dev/$DEVSHELL_PROJECT_ID/rest-api-repo/frontend-production:0.1 \
--platform managed \
--region=$REGION \
--max-instances=1 \
--allow-unauthenticated \
--quiet



export SERVICE_URL=$(gcloud run services describe netflix-dataset-service \
--region=$REGION \
--format='value(status.url)')

# TASK 5
cd ~/pet-theory/lab06/firebase-frontend

gcloud builds submit \
--tag $REGION-docker.pkg.dev/$DEVSHELL_PROJECT_ID/rest-api-repo/frontend-staging:0.1

gcloud run deploy frontend-staging-service \
--image $REGION-docker.pkg.dev/$DEVSHELL_PROJECT_ID/rest-api-repo/frontend-staging:0.1 \
--platform managed \
--region=$REGION \
--allow-unauthenticated \
--max-instances=1

# TASK 6
cd ~/pet-theory/lab06/firebase-frontend/public

sed -i "s|const REST_API_SERVICE = .*|const REST_API_SERVICE = '$SERVICE_URL';|g" app.js

sed -i "s|\${REST_API_SERVICE}/\${year}|\${REST_API_SERVICE}/\${year}|g" app.js

cd ~/pet-theory/lab06/firebase-frontend

gcloud builds submit \
--tag $REGION-docker.pkg.dev/$DEVSHELL_PROJECT_ID/rest-api-repo/frontend-production:0.1

gcloud run deploy frontend-production-service \
--image $REGION-docker.pkg.dev/$DEVSHELL_PROJECT_ID/rest-api-repo/frontend-production:0.1 \
--platform managed \
--region=$REGION \
--allow-unauthenticated \
--max-instances=1
