#!/bin/bash

export REGION=$(gcloud compute project-info describe \
--format="value(commonInstanceMetadata.items[google-compute-default-region])")

export DATASET_SERVICE=netflix-dataset-service
export FRONTEND_STAGING_SERVICE=frontend-staging-service
export FRONTEND_PRODUCTION_SERVICE=frontend-production-service

# TASK 3 - REST API 0.1

cd ~/pet-theory/lab06/firebase-rest-api/solution-01

npm install

gcloud artifacts repositories create rest-api-repo \
--repository-format=docker \
--location=$REGION

gcloud builds submit \
--tag gcr.io/$DEVSHELL_PROJECT_ID/rest-api:0.1 .

gcloud run deploy $DATASET_SERVICE \
--image gcr.io/$DEVSHELL_PROJECT_ID/rest-api:0.1 \
--platform managed \
--region=$REGION \
--allow-unauthenticated \
--max-instances=1 \
--quiet

SERVICE_URL=$(gcloud run services describe $DATASET_SERVICE \
--region=$REGION \
--format='value(status.url)')

curl -X GET $SERVICE_URL

# TASK 4 - REST API 0.2

cd ~/pet-theory/lab06/firebase-rest-api/solution-02

npm install

gcloud builds submit \
--tag gcr.io/$DEVSHELL_PROJECT_ID/rest-api:0.2 .

gcloud run deploy $DATASET_SERVICE \
--image gcr.io/$DEVSHELL_PROJECT_ID/rest-api:0.2 \
--platform managed \
--region=$REGION \
--allow-unauthenticated \
--max-instances=1 \
--quiet

SERVICE_URL=$(gcloud run services describe $DATASET_SERVICE \
--region=$REGION \
--format='value(status.url)')

curl -X GET $SERVICE_URL/2019

# TASK 5 - STAGING FRONTEND

cd ~/pet-theory/lab06/firebase-frontend

npm install
npm run build

gcloud builds submit \
--tag gcr.io/$DEVSHELL_PROJECT_ID/frontend-staging:0.1 .

gcloud run deploy $FRONTEND_STAGING_SERVICE \
--image gcr.io/$DEVSHELL_PROJECT_ID/frontend-staging:0.1 \
--platform managed \
--region=$REGION \
--allow-unauthenticated \
--max-instances=1 \
--quiet

gcloud run services describe $FRONTEND_STAGING_SERVICE \
--region=$REGION \
--format='value(status.url)'

# TASK 6 - PRODUCTION FRONTEND

cd ~/pet-theory/lab06/firebase-frontend/public

sed -i "s#const REST_API_SERVICE = \".*\"#const REST_API_SERVICE = \"$SERVICE_URL/2020\"#g" app.js

cd ..

gcloud builds submit \
--tag gcr.io/$DEVSHELL_PROJECT_ID/frontend-production:0.1 .

gcloud run deploy $FRONTEND_PRODUCTION_SERVICE \
--image gcr.io/$DEVSHELL_PROJECT_ID/frontend-production:0.1 \
--platform managed \
--region=$REGION \
--allow-unauthenticated \
--max-instances=1 \
--quiet

gcloud run services describe $FRONTEND_PRODUCTION_SERVICE \
--region=$REGION \
--format='value(status.url)'
